// <auto-generated />
using System;
using Magazin_Grafuri.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagazinGrafuri.Migrations
{
    [DbContext(typeof(MagazinDbContext))]
    [Migration("20230203180830_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Magazin_Grafuri.Tabele.Angajati", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAngajari")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OreLucratePeSaptamana")
                        .HasColumnType("int");

                    b.Property<int>("OreSuplimentare")
                        .HasColumnType("int");

                    b.Property<string>("Pozitie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Salariu")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("Magazin_Grafuri.Tabele.Dashboard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProduseVanduteAnual")
                        .HasColumnType("int");

                    b.Property<int>("ProduseVanduteLunar")
                        .HasColumnType("int");

                    b.Property<int>("Tranzactie")
                        .HasColumnType("int");

                    b.Property<int>("VenitAnual")
                        .HasColumnType("int");

                    b.Property<int>("VenitLunar")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Dashboard");
                });

            modelBuilder.Entity("Magazin_Grafuri.Tabele.Produse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("Magazin_Grafuri.Tabele.VanzariSaptamanale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProduseVandute")
                        .HasColumnType("int");

                    b.Property<int>("ProfitPeZi")
                        .HasColumnType("int");

                    b.Property<int>("Vanzari")
                        .HasColumnType("int");

                    b.Property<string>("Zi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("VanzariSaptamanale");
                });

            modelBuilder.Entity("Magazin_Grafuri.Tabele.VanzariTotale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.Property<string>("Luna")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("vanzariTotale")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("VanzariToatale");
                });
#pragma warning restore 612, 618
        }
    }
}
